export default function StatsSection() {
  const stats = [
    {
      number: '500+',
      highlight: '+',
      title: 'AI-Powered Websites',
      subtitle:
        'We have empowered businesses of all sizes to launch stunning, high-performance websites with speed and precision.',
    },
    {
      number: '1,000+',
      highlight: '+',
      title: 'Successful Projects',
      subtitle:
        'Our AI has assisted in thousands of projects, combining efficiency with human creativity to deliver exceptional results.',
    },
    {
      number: '10M',
      highlight: '+',
      title: 'Lines of Code Written',
      subtitle:
        'Behind every WebRakor site, millions of lines of code are generated by our AI to ensure a flawless, custom digital experience.',
    },
  ];

  return (
    <section className="pt-0 pb-10 px-4 sm:px-6 lg:px-8 bg-white">
      <div className="max-w-7xl mx-auto">
        
        {/* Heading */}
        <div className="text-center mb-8 sm:mb-10">
          <h2 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-gray-900 leading-tight">
            Focus on your business.<br />We'll build your website.
          </h2>
          <p className="text-sm sm:text-base md:text-lg text-gray-600 max-w-2xl mx-auto mt-4">
            Experience AI-powered speed and human-crafted quality, making web development simpler than ever.
          </p>
        </div>

        {/* Statistics Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8 sm:gap-6 lg:gap-12">
          {stats.map((stat, index) => (
            <div key={index} className="text-center px-2 sm:px-4">
              <div className="text-3xl sm:text-4xl md:text-5xl font-bold text-black mb-1 sm:mb-3">
                {stat.number.replace(stat.highlight, '')}
                <span className="text-[#a3e635]">{stat.highlight}</span>
              </div>
              <h3 className="text-base sm:text-lg md:text-xl font-bold text-black mb-1 sm:mb-2">
                {stat.title}
              </h3>
              <p className="text-xs sm:text-sm md:text-base text-gray-600 leading-snug sm:leading-relaxed">
                {stat.subtitle}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}